/*
 * generated by Xtext 2.28.0
 */
package com.espressif.idf.componen;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class IDFComponentDslStandaloneSetup extends IDFComponentDslStandaloneSetupGenerated {

	public static void doSetup() {
		new IDFComponentDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
