/*
 * generated by Xtext 2.28.0
 */
package com.espressif.idf.componen.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractIDFComponentDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(com.espressif.idf.componen.iDFComponentDsl.IDFComponentDslPackage.eINSTANCE);
		return result;
	}
}
