/*
 * generated by Xtext 2.28.0
 */
package com.espressif.idf.componen.ide;


/**
 * Use this class to register ide components.
 */
public class IDFComponentDslIdeModule extends AbstractIDFComponentDslIdeModule {
}
