/*
 * generated by Xtext 2.28.0
 */
package com.espressif.idf.componen.parser.antlr;

import com.espressif.idf.componen.parser.antlr.internal.InternalIDFComponentDslParser;
import com.espressif.idf.componen.services.IDFComponentDslGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class IDFComponentDslParser extends AbstractAntlrParser {

	@Inject
	private IDFComponentDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalIDFComponentDslParser createParser(XtextTokenStream stream) {
		return new InternalIDFComponentDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ComponentModel";
	}

	public IDFComponentDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(IDFComponentDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
