/*
 * generated by Xtext 2.28.0
 */
package com.espressif.idf.componen.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class IDFComponentDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/espressif/idf/componen/parser/antlr/internal/InternalIDFComponentDsl.tokens");
	}
}
