/**
 * generated by Xtext 2.28.0
 */
package com.espressif.idf.componen.iDFComponentDsl.impl;

import com.espressif.idf.componen.iDFComponentDsl.IDF;
import com.espressif.idf.componen.iDFComponentDsl.IDFComponentDslPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>IDF</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IDFImpl extends FeatureImpl implements IDF
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IDFImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IDFComponentDslPackage.Literals.IDF;
  }

} //IDFImpl
