/**
 * generated by Xtext 2.28.0
 */
package com.espressif.idf.componen.iDFComponentDsl.impl;

import com.espressif.idf.componen.iDFComponentDsl.IDFComponentDslPackage;
import com.espressif.idf.componen.iDFComponentDsl.OVERRIDE_PATH;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>OVERRIDE PATH</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OVERRIDE_PATHImpl extends FeatureImpl implements OVERRIDE_PATH
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OVERRIDE_PATHImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IDFComponentDslPackage.Literals.OVERRIDE_PATH;
  }

} //OVERRIDE_PATHImpl
