/**
 * generated by Xtext 2.28.0
 */
package com.espressif.idf.componen.iDFComponentDsl.impl;

import com.espressif.idf.componen.iDFComponentDsl.IDFComponentDslPackage;
import com.espressif.idf.componen.iDFComponentDsl.PUBLIC;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>PUBLIC</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PUBLICImpl extends COMPONENT_NAME_FEATUREImpl implements PUBLIC
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PUBLICImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IDFComponentDslPackage.Literals.PUBLIC;
  }

} //PUBLICImpl
