/*
 * generated by Xtext 2.28.0
 */
package com.espressif.idf.componen.serializer;

import com.espressif.idf.componen.services.IDFComponentDslGrammarAccess;
import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class IDFComponentDslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected IDFComponentDslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_COMMENT_DependenciesComp_DependenciesKeyword_0_or_NumberSignKeyword_0;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (IDFComponentDslGrammarAccess) access;
		match_COMMENT_DependenciesComp_DependenciesKeyword_0_or_NumberSignKeyword_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getCOMMENTAccess().getNumberSignKeyword_0()), new TokenAlias(false, false, grammarAccess.getDependenciesCompAccess().getDependenciesKeyword_0()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_COMMENT_DependenciesComp_DependenciesKeyword_0_or_NumberSignKeyword_0.equals(syntax))
				emit_COMMENT_DependenciesComp_DependenciesKeyword_0_or_NumberSignKeyword_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     '#' | 'dependencies:'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 
	 * </pre>
	 */
	protected void emit_COMMENT_DependenciesComp_DependenciesKeyword_0_or_NumberSignKeyword_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
