/*
 * generated by Xtext 2.28.0
 */
package com.espressif.idf.componen.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractIDFComponentDslScopeProvider extends DelegatingScopeProvider {
}
