/**
 * generated by Xtext 2.28.0
 */
package com.espressif.idf.componen.iDFComponentDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>COMPONENT NAME FEATURE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.espressif.idf.componen.iDFComponentDsl.COMPONENT_NAME_FEATURE#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see com.espressif.idf.componen.iDFComponentDsl.IDFComponentDslPackage#getCOMPONENT_NAME_FEATURE()
 * @model
 * @generated
 */
public interface COMPONENT_NAME_FEATURE extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.espressif.idf.componen.iDFComponentDsl.IDFComponentDslPackage#getCOMPONENT_NAME_FEATURE_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.espressif.idf.componen.iDFComponentDsl.COMPONENT_NAME_FEATURE#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // COMPONENT_NAME_FEATURE
