/**
 * generated by Xtext 2.28.0
 */
package com.espressif.idf.componen.iDFComponentDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.espressif.idf.componen.iDFComponentDsl.ComponentModel#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see com.espressif.idf.componen.iDFComponentDsl.IDFComponentDslPackage#getComponentModel()
 * @model
 * @generated
 */
public interface ComponentModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link com.espressif.idf.componen.iDFComponentDsl.Type}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see com.espressif.idf.componen.iDFComponentDsl.IDFComponentDslPackage#getComponentModel_Elements()
   * @model containment="true"
   * @generated
   */
  EList<Type> getElements();

} // ComponentModel
