/**
 * generated by Xtext 2.28.0
 */
package com.espressif.idf.componen.iDFComponentDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>COMPONENT NAME</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.espressif.idf.componen.iDFComponentDsl.COMPONENT_NAME#getFeatures <em>Features</em>}</li>
 * </ul>
 *
 * @see com.espressif.idf.componen.iDFComponentDsl.IDFComponentDslPackage#getCOMPONENT_NAME()
 * @model
 * @generated
 */
public interface COMPONENT_NAME extends Feature
{
  /**
   * Returns the value of the '<em><b>Features</b></em>' containment reference list.
   * The list contents are of type {@link com.espressif.idf.componen.iDFComponentDsl.COMPONENT_NAME_FEATURE}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Features</em>' containment reference list.
   * @see com.espressif.idf.componen.iDFComponentDsl.IDFComponentDslPackage#getCOMPONENT_NAME_Features()
   * @model containment="true"
   * @generated
   */
  EList<COMPONENT_NAME_FEATURE> getFeatures();

} // COMPONENT_NAME
