/**
 * generated by Xtext 2.28.0
 */
package com.espressif.idf.componen.iDFComponentDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>IDF</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.espressif.idf.componen.iDFComponentDsl.IDFComponentDslPackage#getIDF()
 * @model
 * @generated
 */
public interface IDF extends Feature
{
} // IDF
