/**
 * generated by Xtext 2.28.0
 */
package com.espressif.idf.componen.iDFComponentDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>OVERRIDE PATH</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.espressif.idf.componen.iDFComponentDsl.IDFComponentDslPackage#getOVERRIDE_PATH()
 * @model
 * @generated
 */
public interface OVERRIDE_PATH extends Feature
{
} // OVERRIDE_PATH
