/**
 * generated by Xtext 2.28.0
 */
package com.espressif.idf.componen.iDFComponentDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PUBLIC</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.espressif.idf.componen.iDFComponentDsl.IDFComponentDslPackage#getPUBLIC()
 * @model
 * @generated
 */
public interface PUBLIC extends COMPONENT_NAME_FEATURE
{
} // PUBLIC
