/**
 * generated by Xtext 2.28.0
 */
package com.espressif.idf.componen.iDFComponentDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>RULES</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.espressif.idf.componen.iDFComponentDsl.IDFComponentDslPackage#getRULES()
 * @model
 * @generated
 */
public interface RULES extends COMPONENT_NAME_FEATURE
{
} // RULES
