/**
 * generated by Xtext 2.28.0
 */
package com.espressif.idf.componen.iDFComponentDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.espressif.idf.componen.iDFComponentDsl.IDFComponentDslPackage#getType()
 * @model
 * @generated
 */
public interface Type extends EObject
{
} // Type
