/**
 * generated by Xtext 2.28.0
 */
package com.espressif.idf.componen.iDFComponentDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>URL</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.espressif.idf.componen.iDFComponentDsl.URL#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see com.espressif.idf.componen.iDFComponentDsl.IDFComponentDslPackage#getURL()
 * @model
 * @generated
 */
public interface URL extends Type
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.espressif.idf.componen.iDFComponentDsl.IDFComponentDslPackage#getURL_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.espressif.idf.componen.iDFComponentDsl.URL#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // URL
