/*
 * generated by Xtext 2.28.0
 */
package com.espressif.idf.componen.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class IDFComponentDslUiModule extends AbstractIDFComponentDslUiModule {

	public IDFComponentDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
