name: Issue Management

on:
  issues:
    types: [opened, edited]

jobs:
  sync_issues_to_jira:
    name: Sync issues to Jira
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Sync GitHub issues to Jira project
        uses: espressif/github-actions/sync_issues_to_jira@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_PASS: ${{ secrets.JIRA_PASS }}
          JIRA_PROJECT: IEP
          JIRA_COMPONENT: GitHub
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER: ${{ secrets.JIRA_USER }}

  docs_bot:
    name: Generate automated response by docs bot
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'espressif' }} # Avoid failures in forked projects
    steps:
      - name: Docs bot action
        uses: espressif/docs-bot-action@master
        env:
          BOT_API_KEY: ${{ secrets.BOT_API_KEY }}
          BOT_INTEGRATION_ID: ${{ secrets.BOT_INTEGRATION_ID }}
          BOT_API_ENDPOINT: ${{ secrets.BOT_API_ENDPOINT }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ github.repository }}
          github_issue_number: ${{ github.event.issue.number }}
          in_msg: ${{ github.event.issue.body }}
          title: ${{ github.event.issue.title }}
          bot_query_prefix: >
            The user has reported an issue related to Espressif-IDE (idf-eclipse-plugin), an Eclipse-based IDE for ESP-IDF development.

            As a bot, first check for existing discussions and solutions in these sources:
            - ESP32 forum (IDE section): https://www.esp32.com/viewforum.php?f=40
            - GitHub issues: https://github.com/espressif/idf-eclipse-plugin/issues

            Provide a concise response based on relevant findings.
            Avoid linking to unrelated GitHub repositories.
          prefix_out_msg: >
            Hi @${{ github.event.issue.user.login }}! This is an automated response.

            If you don’t find the answer helpful, please check the ESP32 IDE forum (https://www.esp32.com/viewforum.php?f=40) or GitHub issues (https://github.com/espressif/idf-eclipse-plugin/issues) to see if the issue has already been discussed.
