name: Issue Management

on:
  issues:
    types: [opened, edited]

jobs:
  sync_issues_to_jira:
    name: Sync issues to Jira
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Sync GitHub issues to Jira project
        uses: espressif/github-actions/sync_issues_to_jira@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_PASS: ${{ secrets.JIRA_PASS }}
          JIRA_PROJECT: IEP
          JIRA_COMPONENT: GitHub
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER: ${{ secrets.JIRA_USER }}

  docs_bot:
    name: Generate automated response by docs bot
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'espressif' }} # Avoid failures in forked projects
    steps:
      - name: Docs bot action
        uses: espressif/docs-bot-action@master
        env:
          BOT_API_KEY: ${{ secrets.BOT_API_KEY }}
          BOT_INTEGRATION_ID: ${{ secrets.BOT_INTEGRATION_ID }}
          BOT_API_ENDPOINT: ${{ secrets.BOT_API_ENDPOINT }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ github.repository }}
          github_issue_number: ${{ github.event.issue.number }}
          in_msg: ${{ github.event.issue.body }}
          title: ${{ github.event.issue.title }}
          prefix_out_msg: >
            Hi @${{ github.event.issue.user.login }}! This is an automated answer.