name: run_idf_installer_build

on:
  release:
    types:
      - published
  pull_request:
  
jobs:
  run-idf-installer-build:
    name: IDF Installer Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Trigger the Receiver Action
        run: |
           curl -XPOST -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
           -H "Accept: application/vnd.github.everest-preview+json" \
           "https://api.github.com/repos/espressif/idf-installer/dispatches" \
           -d '{"event_type": "trigger-action", "client_payload": {"input_name": "value_here"}}'
