name: run_idf_installer_build

on:
  release:
    types:
      - published
  pull_request:
  
jobs:
  run-idf-installer-build:
    name: IDF Installer Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get IDE version from release tag
        run: |
          TAG=${{ github.event.release.tag_name }}
          IDE_VERSION=${TAG#v}
          echo "IDE Version is $IDE_VERSION"
          echo "IDE_VERSION=$IDE_VERSION" >> $GITHUB_ENV

      - name: Get latest release from espressif/esp-idf
        run: |
            RESPONSE=$(curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.REPO_ACCESS_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/espressif/esp-idf/releases/latest)
  
            TAG_NAME=$(echo "$RESPONSE" | jq -r '.tag_name')
            IDF_VERSION=${TAG_NAME#v}
            echo "Latest IDF Version is: $IDF_VERSION"
            echo "IDF_VERSION=$IDF_VERSION" >> $GITHUB_ENV
  

      - name: Trigger the Receiver Action
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.REPO_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/espressif/idf-installer/actions/workflows/build-espressif-ide-installer.yml/dispatches \
            -d '{
               "ref": "main",
              "inputs": {
                   "espressif_ide_version": "'$IDE_VERSION'",
                   "esp_idf_version": "'$IDF_VERSION'",
                   "python_version": "3.11"
              }
            }'

